### ISSUE TITLE
the method of limiting the candidate entities

### ISSUE THREAD

**Issue by JiyaoWei** [xwhan/One-shot-Relational-Learning#16]
Hello, Wenhan

Can you help me understand the method of limiting the candidate entities, in "One-Shot Relational Learning for Knowledge Graphs". Many people cited your paper, but they have not given a specific parameters.

How did you make specific restrictions in your experiment? Can you show your code for generating the candidate set?

Looking forward to your reply!

**Comment by shelleyyyyu** [comment]
hi, do u have the code for generating the candidate set? thanks a lot

**Comment by yoyozz88** [comment]
@JiyaoWei Hi, could you please share the method of limiting the candidate entities you found? Thanks.
