### ISSUE TITLE
The problem of datasets

### ISSUE THREAD

**Issue by dtjayaaa12345** [xwhan/One-shot-Relational-Learning#3]
Hi, Wenhan:
   Why the number of relations contained in Nell dataset (582) is not consistent with the number paper reported (358)?

**Comment by xwhan** [comment]
Hi,

In the dataset, the number 582 indicates the total number of background relations (those are not considered as few-shot learning tasks). Also 582 includes inverse relations, which means that the total number of background relations is 582 // 2. If you add 582//2 with the number of task relations (67), you will get the number 358.
