### ISSUE TITLE
Finding Wikipedia entities

### ISSUE THREAD

**Issue by h4ste** [xwhan/One-shot-Relational-Learning#4]
Hi, I am trying to link the pretraining entity embeddings to their corresponding Wikipedia entities. However, in the Wiki.tar.gz file, the ent2ids file only includes entity names such as "Q15140126". How do I map these names to their actual entity in Wikipedia?

**Comment by xwhan** [comment]
Hi, 

[https://pypi.org/project/Wikidata/](https://pypi.org/project/Wikidata/)

this tool could be useful
