### ISSUE TITLE
entity candidate of Wiki data

### ISSUE THREAD

**Issue by chuxuzhang** [xwhan/One-shot-Relational-Learning#5]
Hi Wenhan,

May I ask how do you generate entity candidate of Wiki data?
Where is the instance_of file in data?
Thanks.

**Comment by xwhan** [comment]
Hi Chuxu, 

As mentioned in the paper, the candidate entities are the entities that have the same type as the answer entity (Section 3.1). To find the type of an entity, we look up the "instance_of" relation triples. The wikidata ID for "instance of " is P31. You can get the raw wikidata dump and get all the triples with P31. That's how we get the instance_of file. 

Best of luck,

**Comment by chuxuzhang** [comment]
understand, thanks.
