### ISSUE TITLE
The url of data sets can't be connected, whatever way I tried. The address of nlp.cs.ucsb.edu is not available. Please change the download address

### ISSUE THREAD

**Issue by IanLiYi1996** [xwhan/One-shot-Relational-Learning#7]

**Comment by IanLiYi1996** [comment]
Hi Wenhan,

When I tried to download the data sets, I found it cannot be connected. I tried to use VPN to reconnect, but  it seems don't work. Could you please offer us a new link to let us have access to the data.

Thank you, best wishes

**Comment by xwhan** [comment]
Hi,

That's because we were updating our servers. Now you should be able to access it.

**Comment by IanLiYi1996** [comment]
Thank you very much, I'm very appreciate what you have done
