### ISSUE TITLE
Invalid pre-trained embeddings download link

### ISSUE THREAD

**Issue by qibinc** [xwhan/One-shot-Relational-Learning#9]
Hi @xwhan ,

I really liked your paper and enjoyed reading it. However, I found the download link for pre-trained embeddings in the README is broken again.

http://nlp.cs.ucsb.edu/data/Wiki/wiki_emb.tar.gz
http://nlp.cs.ucsb.edu/data/NELL/nell_emb.tar.gz

I hope you could fix the links. Thanks in advance!

**Comment by sxrczh** [comment]
Hi @xwhan ,

I really liked your paper and enjoyed reading it. However, I found the download link for pre-trained embeddings in the README is broken again.

http://nlp.cs.ucsb.edu/data/Wiki/wiki_emb.tar.gz
http://nlp.cs.ucsb.edu/data/NELL/nell_emb.tar.gz

I hope you could fix the links. Thanks in advance!

**Comment by xwhan** [comment]
Please use the updated links in readme.

**Comment by sxrczh** [comment]
Thank you！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wenhan Xiong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月26日(星期六) 凌晨3:34
收件人:&nbsp;"xwhan/One-shot-Relational-Learning"<One-shot-Relational-Learning@noreply.github.com&gt;;
抄送:&nbsp;"理工计算"<595260891@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xwhan/One-shot-Relational-Learning] Invalid pre-trained embeddings download link (#9)




Closed #9.
